services:
  db:
    image: mysql:8.0
    container_name: go_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/:ro
    networks:
      - go_network
  api:
    build: .
    container_name: go_api
    depends_on:
      - db
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: 3306
      PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - go_network

networks:
  go_network: